CREATE TABLE `GENRE` (
  `GENRE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `GENRE` varchar(20) NOT NULL,
  PRIMARY KEY (`GENRE_ID`)
);


CREATE TABLE `PUBLISHER` (
  `PUBLISHER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` varchar(30) DEFAULT NULL,
  `NAME` varchar(20) NOT NULL,
  `PHONE` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`PUBLISHER_ID`)
);


CREATE TABLE IF NOT EXISTS `AUTHOR` (
  `AUTHOR_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(30) NULL DEFAULT NULL,
  `FIRST_NAME` VARCHAR(20) NOT NULL,
  `LAST_NAME` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`AUTHOR_ID`)
);

CREATE TABLE `BOOK` (
  `BOOK_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `ISBN_NO` VARCHAR(15) NOT NULL,
  `PRICE` DOUBLE NOT NULL,
  `PUBLISHED_DATE` DATE NULL DEFAULT NULL,
  `SHORT_DESC` VARCHAR(100) NOT NULL,
  `PUBLISHER_ID` INT(11) NOT NULL,
  PRIMARY KEY (`BOOK_ID`),
  FOREIGN KEY (`PUBLISHER_ID`)
  REFERENCES `PUBLISHER` (`PUBLISHER_ID`)
);

CREATE TABLE `BOOK_AUTHOR` (
  `AUTHOR_ID` int(11) NOT NULL,
  `BOOK_ID` int(11) NOT NULL,
  PRIMARY KEY (`AUTHOR_ID`,`BOOK_ID`),
  FOREIGN KEY (`BOOK_ID`) 
    REFERENCES `BOOK` (`BOOK_ID`),
  FOREIGN KEY (`AUTHOR_ID`) 
    REFERENCES `AUTHOR` (`AUTHOR_ID`)
);

CREATE TABLE `BOOK_GENRE` (
  `BOOK_ID` int(11) NOT NULL,
  `GENRE_ID` int(11) NOT NULL,
  PRIMARY KEY (`BOOK_ID`,`GENRE_ID`),
  FOREIGN KEY (`BOOK_ID`) 
    REFERENCES `BOOK` (`BOOK_ID`),
  FOREIGN KEY (`GENRE_ID`) 
    REFERENCES `GENRE` (`GENRE_ID`)
);


