#!/bin/bash

. ./imageName

mkdir -p .eclipse-docker

docker run -ti --rm \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v `pwd`:/workspace \
           $IMAGE_NAME
