FROM org.tecris:5000/wildfly-mysql:9.0.2

ENV MAVEN_GROUP_ID org.bs
ENV MAVEN_ARTIFACT_ID bookstore

ENV MAVEN_NEXUS_REPO_URL 172.17.0.2

RUN wget "http://${MAVEN_NEXUS_REPO_URL}:8081/service/local/artifact/maven/redirect?r=snapshots&g=${MAVEN_GROUP_ID}&a=${MAVEN_ARTIFACT_ID}&v=LATEST&e=war" -O /opt/jboss/wildfly/standalone/deployments/bookstore.war 
