FROM 192.168.1.66:5000/wildfly82

RUN wget http://192.168.1.66:8081/content/repositories/snapshots/org/tecris/sample/rest.jax-rs/1.1-SNAPSHOT/rest.jax-rs-1.1-20150509.041710-1.war -O /opt/jboss/wildfly/standalone/deployments/ROOT.war

